#raise Exception("This is a manually raised exception!")

#raise SyntaxError("Syntax error")

#try:
 #   myList = []
    #print("paleidziam koda try blocke")
 #   myList = (1)


#except:
 #   print("printinam kazka")

