#raise Exception("This is a manually raised exception!")

#raise SyntaxError("Syntax error")

# try:
    # myList = []
    # print("paleidziam koda try blocke")
    # myList[0]
# except IndexError:
    # print("printinam kazka")

# funkcijos kurimas
    def random_exeption():
        print("")